### ISSUE TITLE
Cascading Worldgen Lag

### ISSUE THREAD

**Issue by dninemfive** [EpicSquid/MysticalWorld#21]
I get this error when loading worlds in which your structures generate (I don't, for example, get it in void worlds). 

```
[19:32:54] [Server thread/WARN] [FML]: Mystical World loaded a new chunk [13, -43] in dimension 0 (overworld) while populating chunk [14, -43], causing cascading worldgen lag.
[19:32:54] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
```

Seems to be caused by [this](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/) issue.

**Comment by duely** [comment]
This just means that the work I did to allow for structures to generate and place blocks near the border of the chunk and not potentially chunkload adjacent chunks for light checks is failing on me. Sorry about that.

However, this is an extremely minor thing as it is not *cascading*, as it only loads one additional chunk (not many). Unless this is happening extremely frequently it's not something that you actually need to worry about, because that chunk would've been loaded anyway.

If you are actually getting this repeatedly and constantly then there are significant issues with your world that is causing it to constantly generate structures from Mystical World when it should not be doing so. If that is the case, please attach the complete log file and I'll take a look at it.

Otherwise, if you have issues, I'd recommend looking into other avenues as this is not likely to be one that is causing you problems or server lag. If on the other hand you were just wanting to let us know, thanks! It is appreciated that people take the time to report these things.

Unfortunately, the default message "you should report this" that comes along with it is very misleading because sometimes there's literally no way to avoid it. 

(Also, For an example of huge world generation chunk lag I recommend installing Better Nether and running it on default settings and stepping through a Nether Portal in single player. You'll see from the logs that it is actually *cascading* and each subsequently loaded chunk is causing more chunks to load, etc.)
